# Basic
title: Maco
subtitle: 闭花羞月
welcome_message: #<a href="https://objccn.io/products/">我组织的 ObjC 中国与 objc.io 合作发布了一系列 iOS/Swift 相关图书，欢迎访问了解更多</a>
description: 嗨，我是张志方 (@Maco)，一名 iOS 开发者。
creator: <a href="https://superhaifeng.github.io">@Maco</a>
encoding: UTF-8

url: "https://superhaifeng.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

blog_button:
    title: 博客
    description: 访问博客

nav:
    #- {title: 简历, description: 我的简历, url: '//onev.cat'}
    #- {title: 工具, description: 我所使用的 app 们, url: '/apps'}
    #- {title: 订阅, description: 邮件订阅本站, url: '//objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Maco
    # duoshuo:
# Social
social:
    weibo: 1804548547
    github: SuperHaiFeng
    twitter: Macode520
    #gplus: 107108267983477358170
    mail: zhangzhifang1013@gmail.com
    facebook: Swifal
    linkedIn: maco-zhang-1239ba146

# Google Analytics

ga:
   id: UA-148217509-1
   host: superhaifeng.github.io
